require: rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/*'
    - 'tmp/*'
    - 'storage/*'
    - 'config/**/*'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'Gemfile'
    - 'app/assets/*'
    - 'public/*'
    - 'app/javascript/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'coverage/*'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 140

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Max: 40
  ExcludedMethods: ['describe','context']

RSpec/MultipleExpectations:
  Max: 3

RSpec/NamedSubject:
  Enabled: false

RSpec/ExampleLength:
  Max: 7








