require: rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/*'
    - 'tmp/*'
    - 'storage/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'public/*'
    - 'coverage/*'
    - bin/bundle
    - config/initializers/devise.rb

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Max: 40
  ExcludedMethods: ['describe','context']

RSpec/MultipleExpectations:
  Max: 1
  Exclude:
  - 'spec/features/**/*'
  - 'spec/controllers/**/*'

RSpec/ExampleLength:
  Max: 7

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/AbcSize:
  Exclude:
  - 'spec/features/**/*'
