version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers-legacy
        environment:
          RAILS_ENV: test
      - image: circleci/postgres:12.1
          environment:
            POSTGRES_USER: pguser
            POSTGRES_DB: bookstore_test
            POSTGRES_PASSWORD: root
            DATABASE_URL: "postgres://ubuntu@localhost:5432/bookstore_test"
    steps:
      - checkout

      - restore_cache:
          keys:
            - gem-cache-v1-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1-

      - run:
          name: Install dependencies
          command: |
            gem install bundler
            bundle install --path vendor/bundle
      - save_cache:
          key: gem-cache-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Run tests
          command: bundle exec rspec



